
#Nom de la route
store_backend_index:
    path: / #chemin / URI de la route
    defaults: { _controller: StoreBackendBundle:Main:index }
    # Le Controlleur et L'action appelée

#Pages Statics
store_backend_statics:
    resource: "@StoreBackendBundle/Resources/config/statics.yml"
    prefix:   /

#Pages Products
store_backend_products:
    resource: "@StoreBackendBundle/Resources/config/modules/product.yml"
    prefix:   /products

#Pages Orders
store_backend_orders:
    resource: "@StoreBackendBundle/Resources/config/modules/order.yml"
    prefix:   /orders

#Pages Categories
store_backend_categories:
    resource: "@StoreBackendBundle/Resources/config/modules/category.yml"
    prefix:   /categories

#Pages Jeweler
store_backend_jewelers:
    resource: "@StoreBackendBundle/Resources/config/modules/jeweler.yml"
    prefix:   /jewelers

#Pages CMS
store_backend_cms:
    resource: "@StoreBackendBundle/Resources/config/modules/cms.yml"
    #Argument {_locale} pour traduire tout mon module cms
    # au niveau du routing
    # {_locale} : Argument spéciale au routing reconnus par le systeme
    # d'internationalisation de Symfony
    prefix:   /{_locale}/cms
    requirements:
      _locale: en|fr|es

#Pages Suppliers
store_backend_suppliers:
    resource: "@StoreBackendBundle/Resources/config/modules/supplier.yml"
    prefix:   /suppliers

#Pages Slider
store_backend_slider:
    resource: "@StoreBackendBundle/Resources/config/modules/slider.yml"
    prefix:   /slider