<?php

namespace Store\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Get Products of User
     * @param int $user
     * @return array
     */
    public function getCategoryByUser($user){

        $query = $this->getEntityManager()
            ->createQuery(
                "
                    SELECT c
                    FROM StoreBackendBundle:Category c
                    WHERE c.jeweler = :user
                    "
            )
            ->setParameter('user', $user);

        return $query->getResult();
    }

}
