<?php

namespace Store\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsRepository extends EntityRepository
{

    /**
     * Count All CMS
     * @return mixed
     */
    public function getCountByUser($user = null){
        $query = $this->getEntityManager()
            ->createQuery(
                "
                 SELECT COUNT(c) AS nb
                 FROM StoreBackendBundle:CMS c
                 WHERE c.jeweler = :user
                "
            )
            ->setParameter('user', $user);

        return $query->getOneOrNullResult();
    }


}
