<?php

namespace Store\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    /**
     * Count Comment
     * @return mixed
     */
    public function getCountByUser($user = null){
        $query = $this->getEntityManager()
            ->createQuery(
                "
                 SELECT COUNT(c) AS nb
                 FROM StoreBackendBundle:Comment c
                 JOIN c.product p
                 WHERE p.jeweler = :user
                 GROUP BY p.jeweler
                "
            )
            ->setParameter('user', $user);

        return $query->getOneOrNullResult();
    }
}
