<?php

namespace Store\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * Get all product of an user
     * @return mixed
     */
    public function getProductByUser($user = null){
        $query = $this->getEntityManager()
            ->createQuery(
                "
                 SELECT p
                 FROM StoreBackendBundle:Product p
                 WHERE p.jeweler = :jew"
            )
            ->setParameter('jew', $user);

        return $query->getResult();
    }

    /**
     * Count All Product
     * SELECT COUNT(id)
     * FROM `product`
     * WHERE `jeweler_id` = 1
     * @return mixed
     */
    public function getCountByUser($user = null){
        // compte le nb de produits pour 1 bijoutier
        $query = $this->getEntityManager()
            ->createQuery(
                "
                 SELECT COUNT(p) AS nb
                 FROM StoreBackendBundle:Product p
                 WHERE p.jeweler = :user"
            )
            ->setParameter('user', $user);

        // retourne 1 résultat ou null
        return $query->getOneOrNullResult();
    }
}
