<?php

namespace Store\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{
    /**
     * Get all slides of an user.
     *
     * @return mixed
     */
    public function getSlidesByUser($user = null)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                '
                 SELECT s
                 FROM StoreBackendBundle:Slider s
                 JOIN s.product p
                 WHERE p.jeweler = :jew'
            )
            ->setParameter('jew', $user);

        return $query->getResult();
    }
}
