
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~

    # Composant de Traduction à activer si j'ai site multilingue
    # Le paremetre fallbacks à l'intérieur est la langue prise par défaut
    # dans le mecanisme de traduction
    # %locale% est un paremetre définis dans parameters.yml
    translator:      { fallbacks: ['%locale%'] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        gc_probability: 0
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
     - 'StoreBackendBundle:Partial:form.html.twig'

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['StoreBackendBundle']
    #java: /usr/bin/java
    node: /usr/bin/nodejs
    filters:
      uglifyjs2:
          bin: /usr/local/bin/uglifyjs
      uglifycss:
          bin: /usr/local/bin/uglifycss
      cssrewrite: ~
#        closure:
#            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
          default:
            auto_mapping: true
            #Custom AST for DQL
            dql:
              numeric_functions:
                  round: Store\BackendBundle\Doctrine\Extensions\Round
                  truncate: Store\BackendBundle\Doctrine\Extensions\Truncate
              datetime_functions:
                  date_format: Store\BackendBundle\Doctrine\Extensions\DateFormat
              string_functions:
                  month: Store\BackendBundle\Doctrine\Extensions\Month
                  year: Store\BackendBundle\Doctrine\Extensions\Year

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    encryption: ssl
    auth_mode:  login
    host:       %mailer_host%
    username:   %mailer_host%
    password:   %mailer_user%


#KNP Paginator Bundle Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # Nom du parametre mis en URL pagination ?page=1 ...?page=2
        sort_field_name: sort          # Nom du parametre en URL pour le tri
        sort_direction_name: direction # Nom du parametre en URL pour la direction du tri
        distinct: true                 # Pagination de maniere distincte (SQL)
    template:
        # Vue partielle pour mettre en forme la pagination
        pagination: StoreBackendBundle:Partial:sliding.html.twig     # Template de pagination:
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # Template de tri



##Capcha
gregwar_captcha: ~


##FOS Elastica
fos_elastica:
    default_manager: orm
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            index_name: website_qa
            types:
              supplier:
                 mappings:
                   name: {type: string }
                   description: {type: string }
              jeweler:
                 mappings:
                   username: {type: string }
                   email: {type: string }
                   title: {type: string }
                   description: {type: string }
              product:
                mappings:
                    title: { type: string }
                    summary: { type: string }
                    description: { type: string }
                    composition: { type: string }
                    price: { type: string }
                    taxe: { type: string }
                    jeweler:
                      type: "nested"
                      properties:
                         username: {type: string }
                         email: {type: string }
                         title: {type: string }
                         description: {type: string }
                    category:
                      type: "nested"
                      properties:
                         title: {type: string }
                         description: {type: string }
                persistence:
                    driver: orm
                    model: Store\BackendBundle\Entity\Product
                    repository: Store\BackendBundle\Repository\ProductRepository
                    provider:
                        query_builder_method: activeProductQueryBuilder
                    finder: ~
                    listener: ~ # by default, listens to "insert", "update" and "delete"




  #hwi_oauth:
  #    # name of the firewall in which this bundle is active, this setting MUST be set
  #    firewall_name: store_backend
  #    resource_owners:
  #      facebook:
  #        type:                facebook
  #        client_id:           %api_facebook_id%
  #        client_secret:       %api_facebook_secret%