# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    #
    # Encodage dun mot de passe: stratégie
    #
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    #
    # Role des utilisateurs
    #
    role_hierarchy:
        ROLE_JEWELER:       ROLE_JEWELER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin@gmail.com: { password: admin, roles: [ 'ROLE_JEWELER' ] }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # the login page has to be accessible for everybody
        login:
            pattern:  ^/login$
            security: false

        # secures part of the application
        demo_secured_area:
            pattern:    ^/administration
            form_login:
                check_path: store_backend_login_check
                login_path: store_backend_login
                remember_me: true
                target_path_parameter:          store_backend_index
                default_target_path:  /administration
            logout:
                path:   store_backend_logout
                target: /login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/administration, roles: ROLE_JEWELER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
