# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:








#    store.backend.listener.authentification:
#        class: Store\BackendBundle\Listener\AuthenticationListener
#        arguments: ["@doctrine.orm.entity_manager", "@security.context"]
#        tags:
#          - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

#    kernel.listener.find_object:
#        class: Store\BackendBundle\Listener\FindObjectListener
#        arguments: ["@security.context"]
#
#    security.access.object_voter:
#          class:      Store\BackendBundle\Security\Authorization\Voter\ObjectVoter
#          arguments:  [@service_container]
#          public:     false
#          tags:
#            -    { name: security.voter }
