
# Page List of Product
store_backend_product_list:
  path: /list
  defaults: { _controller: StoreBackendBundle:Produit:list }

# Page View a Product
store_backend_product_view:
  path: /view/{id}/{name}
  defaults: { _controller: StoreBackendBundle:Produit:view }
  requirements:
    id: \d+
    _method: GET

# Remove a Product
store_backend_product_remove:
  path: /remove/{id}
  defaults: { _controller: StoreBackendBundle:Produit:remove }

# Page New a Product
store_backend_product_new:
  path: /new
  defaults: { _controller: StoreBackendBundle:Produit:new }
