
# Page List of Product
store_backend_product_list:
  path: /list
  defaults: { _controller: StoreBackendBundle:Produit:list }

# Page View a Product
store_backend_product_view:
  path: /view/{id}/{name}
  defaults: { _controller: StoreBackendBundle:Produit:view }
  requirements:
    id: \d+
    _method: GET

# Remove a Product
store_backend_product_remove:
  path: /remove/{id}
  defaults: { _controller: StoreBackendBundle:Produit:remove }

# Edit a Product
store_backend_product_edit:
  path: /edit/{id}
  defaults: { _controller: StoreBackendBundle:Produit:edit }

# Page New a Product
store_backend_product_new:
  path: /new
  defaults: { _controller: StoreBackendBundle:Produit:new }

# Activate a Product
store_backend_product_activate:
  path: /activate/{id}/{action}
  defaults: { _controller: StoreBackendBundle:Produit:activate }

# Cover a Product
store_backend_product_cover:
  path: /cover/{id}/{action}
  defaults: { _controller: StoreBackendBundle:Produit:cover }
