
# Page List of Supplier
store_backend_supplier_list:
  path: /list
  defaults: { _controller: StoreBackendBundle:Supplier:list }

# Page View a Suppliers
store_backend_supplier_view:
  path: /view/{id}/{name}
  defaults: { _controller: StoreBackendBundle:Supplier:view }
  requirements:
    id: \d+
    name: "[a-zA-Z0-9-]{3,30}"
    _method: GET


# Page new Supplier
store_backend_supplier_new:
  path: /new
  defaults: { _controller: StoreBackendBundle:Supplier:new }

# Page edit Supplier
store_backend_supplier_edit:
  path: /edit/{id}
  defaults: { _controller: StoreBackendBundle:Supplier:edit }

# Page remove Supplier
store_backend_supplier_remove:
  path: /remove/{id}
  defaults: { _controller: StoreBackendBundle:Supplier:remove }